site_name: Almanaque ABAP
site_url: https://bmoreiraribeiro.github.io/ABAP/
theme:
  name: material
  language: pt
  icon:
    logo: icon.png
  favicon: icon.png
  features:
    - navigation.instant     # navegação rápida
    - navigation.top         # botão "voltar ao topo"
    - navigation.tracking    # atualiza URL ao rolar
    - search.suggest         # sugestões na pesquisa
    - search.highlight       # destaca termos pesquisados
    - content.code.copy      # botão copiar código
    - navigation.indexes     # permite clicar nas pastas e abrir index.md
    # NOTA: navigation.expand e navigation.sections foram removidos
    # para permitir navegação colapsável manual com indentação
  palette:
    # --- Modo claro ---
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Modo escuro

    # --- Modo escuro ---
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Modo claro
plugins:
  - search
  - awesome-pages
markdown_extensions:
  - admonition              # ativa caixas de dicas
  - pymdownx.details        # permite colapsar caixas
  - pymdownx.superfences    # permite código dentro das caixas
  - attr_list               # permite atributos como {width=50%}
  - md_in_html              # permite HTML inline
